version: "3"

tasks:
  compile:
    desc: compile traily's backend
    cmds:
      - go build -o bin/traily ./cmd/main.go

  run:
    desc: run traily's api
    deps:
      - compile
    cmds:
      - ./bin/traily

  test:
    desc: run unit tests
    cmds:
      - go test ./...

  test:integration:
    desc: run integration tests with Docker
    cmds:
      - defer: docker compose down
      - docker compose up -d db
      - sleep 10
      - go test -tags=integration -timeout=300s ./internal/domain/... -v

  migrate:
    desc: run pending DB migrations manually
    cmds:
      - go run ./cmd/migrate

  docker:migrate:
    desc: run pending DB migrations manually inside the dev container
    cmds:
      - docker compose exec api go run ./cmd/migrate

  docker:dev:
    desc: run traily's api in dev mode, removing containers on stop
    cmds:
      - defer: docker compose down
      - docker compose up -V --build

  docker:prod:
    desc: run traily's api in prod mode, removing containers on stop
    cmds:
      - defer: docker compose -f docker-compose.prod.yml down
      - docker compose -f docker-compose.prod.yml up --build
